// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ytygqljpkuqxtijiojeg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl0eWdxbGpwa3VxeHRpamlvamVnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI1ODIzNjAsImV4cCI6MjA2ODE1ODM2MH0.del2CiTmuam1wv2eLEL7M8QC4ijjmZjpNH6TqQ0Z5Mc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});